<div id="capcalera">
<p >Aquest notebook complementa els continguts teòrics de l'assignatura d'<strong>Algorísmica</strong> del Grau d'Enginyeria Informàtica a la <a href="https://mat.ub.edu">Facultat de Matemàtiques i Informàtica</a> de la <a href="https://www.ub.edu">Universitat de Barcelona</a></p>

<p>Els problemes s'ofereixen sota llicència <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode">CC-BY-NC-ND license</a>, i el codi sota <a href="https://opensource.org/licenses/MIT">Llicència MIT</a>.</p>

</div>

# Python - Introducció a les List comprehensions

## List comprehensions

Per crear llistes de manera molt eficient, podem usar les list comprehensions.

In [1]:
# Exemple de creació de la llista dels quadrats de 1 a 10 a la manera clàssica
quadrats: list[int] = []
for x in range(10):
    quadrats.append(x ** 2)
print(quadrats)

# Exemple de creació de la llista de quadrats de 1 a 10 amb list comprehensions
quadrats2: list[int] = [x ** 2 for x in range(10)] 
                                    # primer indiquem l'expressió que anirà omplint la llista, 
                                    # després el rang de valors,
                                    # i podem posteriorment indicar altres rangs o condicions
print(quadrats2)

#Tot i que la complexitat és la mateixa, la segona instrucció s'executa més ràpidament i amb menys recursos que la primera

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [6]:
# Exemple 1: Traducció a list comprehension de la següent estructura

combinacions: list[tuple[int]] = []
for x in [1, 2, 3]:
    for y in [3, 1, 4]:
        if x != y:
            combinacions.append((x, y))
print(combinacions)

# combinacions2 = [ expressió que ha d'omplir la llista for més extern, for segon més extern, if]

combinacions2: list[tuple[int]] = [(x, y) for x in [1, 2, 3] for y in [3, 1, 4] if x != y]
print(combinacions2)

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]


Les comprehensions de les llistes són una eina per transformar una llista (qualsevol iterable en realitat) en una altra llista. Durant aquesta transformació, els elements es poden incloure de manera condicional a la nova llista i cada element es pot transformar segons sigui necessari.

Cada comprehension es pot reescriure com un bucle sobre la lista, però no tot bucle es pot reescriure com a list comprehension.

Començant pel cas més senzill, una list comprehension com aquesta:

```python
a = [func(element) for element in sequence]
```

és equivalent a:

```python
a = []
for element in sequence:
    a.append(func(element))
```

De la mateixa manera que podeu afegir `for` addicionals als bucles i condicions `if` dins dels bucles, també podeu afegir-les a la comprensió.

La clau a entendre és que l'ordre d'esquerra a dreta en la comprehennsion assigna el mateix ordre als bucles explícits:

```python
a = [func(element) for subseq in seq2d for element in subseq if pred(element)]

a = []
for subseq in seq2d:
    for element in subseq:
        if pred(element):
            a.append(func(element))
```

També podem usar les list comprehensions per a fer combinacions:

In [8]:
[a+b+c for a in ['A', 'B', 'C'] for b in ['D', 'E', 'F'] for c in ['G', 'H', 'I']]

['ADG',
 'ADH',
 'ADI',
 'AEG',
 'AEH',
 'AEI',
 'AFG',
 'AFH',
 'AFI',
 'BDG',
 'BDH',
 'BDI',
 'BEG',
 'BEH',
 'BEI',
 'BFG',
 'BFH',
 'BFI',
 'CDG',
 'CDH',
 'CDI',
 'CEG',
 'CEH',
 'CEI',
 'CFG',
 'CFH',
 'CFI']

### <span class="exercici">Exercici 1: Escriu en forma de list comprehension les següents llistes</span>

1. Fer una llista amb tots els números fins a 10
2. Fer una llista amb tots ls números fins a 10 múltiples de 2
3. Fer una llista amb totes les parelles (i, j) amb i de 0 a 2 i amb j de 0 a 3
4. Fer una llista amb tots els números divisibles per 3 menors a 20
5. Fer una llista amb tots els números anteriors als divisibles per 3 menors a 20
6. Fer una llista amb totes les parelles de numeros positius menors a 20 que sumin 18
7. Fer una llista amb els múltiples de 3 i 5 menors que 1000. Després calcula la suma de tots els elements de la llista
8. Fer una llista amb els valors de 100 a 1000, múltiples de 10, en ordre invers. És a dir 1000, 990, 980...

In [35]:
l1: list[int] = [i for i in range(11)]
print(l1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
l2: list[int] = [i for i in range(11) if i % 2 == 0]
print(l2)

[0, 2, 4, 6, 8, 10]


In [66]:
l3: list[tuple[int, int]] = [(i, j) for i in range(3) for j in range(4)]
print(l3)

[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]


In [38]:
l4: list[int] = [i for i in range(20) if i % 3 == 0]
print(l4)

[0, 3, 6, 9, 12, 15, 18]


In [65]:
l5: list[int] = [i - 1 for i in range(3, 20, 3)]
print(l5)

[2, 5, 8, 11, 14, 17]


In [59]:
l6: list[tuple[int, int]] = [(i, j) for i in range(1, 20) for j in range(i, 20) if i + j == 18]
print(l6)

[(1, 17), (2, 16), (3, 15), (4, 14), (5, 13), (6, 12), (7, 11), (8, 10), (9, 9)]


In [62]:
l7: list[int] = [i for i in range(0, 1000, 15)]
print(l7)

[0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405, 420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615, 630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825, 840, 855, 870, 885, 900, 915, 930, 945, 960, 975, 990]


In [56]:
l8: list[int] = [i for i in range(1000, 99, -10)]
print(l8)

[1000, 990, 980, 970, 960, 950, 940, 930, 920, 910, 900, 890, 880, 870, 860, 850, 840, 830, 820, 810, 800, 790, 780, 770, 760, 750, 740, 730, 720, 710, 700, 690, 680, 670, 660, 650, 640, 630, 620, 610, 600, 590, 580, 570, 560, 550, 540, 530, 520, 510, 500, 490, 480, 470, 460, 450, 440, 430, 420, 410, 400, 390, 380, 370, 360, 350, 340, 330, 320, 310, 300, 290, 280, 270, 260, 250, 240, 230, 220, 210, 200, 190, 180, 170, 160, 150, 140, 130, 120, 110, 100]


### <span class="exercici">Exercici 1: Escriu en forma de list comprehension les següents llistes</span>

1. Fer una llista amb tots els números fins a 10
2. Fer una llista amb tots ls números fins a 10 múltiples de 2
3. Fer una llista amb totes les parelles (i, j) amb i de 0 a 2 i amb j de 0 a 3
4. Fer una llista amb tots els números divisibles per 3 menors a 20
5. Fer una llista amb tots els números anteriors als divisibles per 3 menors a 20
6. Fer una llista amb totes les parelles de numeros positius menors a 20 que sumin 18
7. Fer una llista amb els múltiples de 3 i 5 menors que 1000. Després calcula la suma de tots els elements de la llista
8. Fer una llista amb els valors de 100 a 1000, múltiples de 10, en ordre invers. És a dir 1000, 990, 980...

l1: list[int] = [i for i in range(11)]
print(l1)
l2: list[int] = [i for i in range(11) if i % 2 == 0]
print(l2)
l3: list[tuple[int, int]] = [(i, j) for i in range(3) for j in range (4)]
print(l3)
l4: list[int] = [i for i in range(20) if i % 3 == 0]
print(l4)
l5: list[int] = [i for i in [j for j in range(20) if j % 3 == 0] if i % 3 == 0]
print(l5)
l6: list[tuple[int, int]] = [(i, j) for i in range(20) for j in range(20) if i + j == 18]
print(l6)
limit: int = int(1000 ** 0.5)
l7: list[int] = [i * j for i in [x for x in range(3, r, 3)] for j in [y for y in range(5, r, 5)]]
print(l7)
# 0 是 3 与 5 的公倍数吗？
l8: list[int] = [i for i in range(1000, 99, -10)]
print(l8)