#  📖 Capítol 5 - Dividir i Vèncer

### 5.24 Xifres i lletres

Considera una llista de cadenes de text amb dos tipus de dades diferentes: cadenes de lletres i cadenes de nombres, com ara la llista ``['aa', '123', 'bc', '98']``. L'objectiu d'aquest problema és ordenar aquesta llista de manera que les cadenes formades per nombres quedin al capdavant. Aquest algorisme no ha de retornar res, només ha de modificar la llista d'entrada.

A la cadena de l'exemple, "123" i "98" han de quedar al davant, en qualsevol ordre, i "aa" i "bc" al darrera, en qualsevol ordre.

✍️ Escriu una funció ``xifres_lletres_ord_sel`` que resolgui el problema usant el mètode d'**ordenació per selecció**. Demostra que la complexitat de l'algorisme que has escrit és $\mathcal{O}(n^2)$.

In [ ]:
# Ordenació per selecció
def xifres_lletres_ord_sel(llista:list[any]):
    """
    Aquesta funció modifica la llista separant lletres i xifres
    
    Parameters
    ----------
    llista: list[any]
    
    Returns
    -------
    llista_ordenada: list[any]
    
    """
    n = len(llista)
    for i in range(n):
        min_pos = i
        for j in range(i+1, n):
            if llista[j].isdecimal() and not llista[min_pos].isdecimal():
                min_pos = j
        llista[i], llista[min_pos] = llista[min_pos], llista[i]

In [44]:
llista = ['aa', '123', 'bc', '98']
xifres_lletres_ord_sel(llista)
print(llista)

['123', '98', 'aa', 'bc']


In [45]:
llista = ["456","789","abc","123","tzu","870","zzz"]
xifres_lletres_ord_sel(llista)
print(llista)

['456', '789', '123', '870', 'zzz', 'tzu', 'abc']


Demostra la complexitat de l'algorisme.

✍️ Escriu una funció ``xifres_lletres_ord_QS`` que resolgui el problema usant tot o part del mètode de ***quicksort***. Demostra que la complexitat de l'algorisme que has éscrit és $\mathcal{O}(n)$.

In [22]:
# quicksort
def xifres_lletres_ord_QS(llista:list[any]):
    """
    Aquesta funció modifica la llista separant lletres i xifres
    
    Parameters
    ----------
    llista: list[any]
    
    Returns
    -------
    llista_ordenada: list[any]
    """
    p_num = -1
    p_alpha = len(llista)

    while True: 
        p_num += 1
        while llista[p_num].isdecimal():
            p_num += 1
        
        p_alpha -= 1
        while llista[p_alpha].isalpha():
            p_alpha -= 1
        
        if p_alpha >= p_num:
            return
        llista[p_num], llista[p_alpha] = llista[p_alpha], llista[p_num]

In [23]:
llista = ["456","789","abc","123","tzu","870","zzz"]
xifres_lletres_ord_sel(llista)
print(llista)

['456', '789', '123', '870', 'abc', 'tzu', 'zzz']


### Asserts públics
En aquest problema no facilitem asserts públics perquè l'ordre no està determinat, l'únic que es demana és que les cadenes formades per nombres quedin al davant. ls mateixos exemples que es donen aquí serveixen per a *xifres_lletres_ord_sel*.

Per exemple a xifres_lletres_ord_QS(["456","789","abc","123","tzu","870","zzz"])

"456", "789", "123" i "870" han de quedar al davant, sense cap ordre determinat

"abc" i "tzu" han de quedar darrera, sense cap ordre determinat.


Per exemple a xifres_lletres_ord_QS(["zzz"]) la llista ha de quedar igual

Per exemple a xifres_lletres_ord_QS(["136"]) la llista ha de quedar igual.

Justifica la complexitat de l'algorisme.